name: Publish nightly release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  create-build-artifacts:
    uses: ./.github/workflows/create-build-artifacts.yml
    secrets: inherit

  create-release:
    needs: "create-build-artifacts"

    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/databricks-vscode

      - run: ls -lR packages/databricks-vscode

      - name: Update nightly release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          name: Nightly - ${{ github.ref_name }}
          prerelease: true
          tag_name: nightly-${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/databricks-vscode/databricks*/*.vsix"
