name: Publish nightly release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  create-build-artifacts:
    uses: ./.github/workflows/create-build-artifacts.yml
    secrets: inherit

  create-release:
    needs: "create-build-artifacts"

    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/databricks-vscode

      - run: ls -lR packages/databricks-vscode

      - name: Update nightly release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: nightly-${{ github.ref_name }}
        run: |
          REPO=databricks/databricks-vscode
          if gh release view "$TAG" --repo "$REPO" &>/dev/null; then
            gh release upload "$TAG" --repo "$REPO" --clobber packages/databricks-vscode/databricks*/*.vsix
          else
            gh release create "$TAG" \
              --repo "$REPO" \
              --title "Nightly - ${{ github.ref_name }}" \
              --prerelease \
              --target "${{ github.sha }}" \
              --notes "Nightly build from ${{ github.ref_name }}" \
              packages/databricks-vscode/databricks*/*.vsix
          fi
